# Generated by Django 4.2.2 on 2024-06-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_time', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('status', models.CharField(choices=[('successful', 'успешно'), ('failed', 'неуспешно')], max_length=50, verbose_name='статус рассылки')),
                ('server_response', models.CharField(max_length=150, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
