# Generated by Django 4.2.2 on 2024-06-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_next_send_time_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempts',
            name='last_attempt_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней попытки'),
        ),
    ]
